#!groovy

// Generated by IBM TransformationAdvisor
// Thu May 09 10:08:36 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}